import './globals.css';
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';

// PROVIDERS
import { AppProvider } from '@/providers/app.provider';

// LIBS
import { cn } from '@/lib/utils';

const font = JetBrains_Mono({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'SCALIS Challenge',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    ...props
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn('bg-slate-50 min-h-screen', font.className)}>
                <AppProvider pageProps={props}>{children}</AppProvider>
            </body>
        </html>
    );
}
